Fix `NoSuchMethodError` due to internal API breakage in sbt >= 1.4
Using runtime reflection, we can avoid having the concrete prototype
of the `defaultScreen` and `withScreenLogger` methods encoded in byte
code.